### PR TITLE
further improvements to handling of pre-computed lead fields

### PR DESCRIPTION
**Pull request by robertoostenveld**
I have made the code more consistent between ft_sourceanalysis and ft_dipolefitting (although differences remain). In ft_sourceanalysis it will now not call `prepare_headmodel` anymore in case precomputed leadfields are present. I believe this to be the required change for more efficiently working with FEM headmodels.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
following the review of @vitpia or @mcpiastra, it can be merged into the `flexsource` branch from Vitoria. Subsequently it can be merged into `fieldtrip: master` via https://github.com/fieldtrip/fieldtrip/pull/1377

**Comment by vitpia** [comment]
> 
> 
> following the review of @vitpia or @mcpiastra, it can be merged into the `flexsource` branch from Vitoria. Subsequently it can be merged into `fieldtrip: master` via [fieldtrip#1377](https://github.com/fieldtrip/fieldtrip/pull/1377)

Should I do this already or wait for you to make more changes?

**Comment by vitpia** [comment]
Tests so far have confirmed that if an empty headmodel and pre-computed leadfields are passed, ft_sourceanalysis will not recompute them. The leadfields in the output of ft_sourceanalysis are the same as in the input, but only for the sensors present in the input data, i.e., the code is correctly checking for inconsistencies between leadfield labels and functional data labels.

**Comment by robertoostenveld** [comment]
I did detect some cases where the code still does not work (e.g. if the order of channels in the precomputed leadfields is different from that in the data). So there is still more work to be done...

**Pull request merged**
